### ISSUE TITLE
Warnings during Docker build

### ISSUE THREAD

**Issue by LilianBoulard** [funmaker/Hybooru#26]
Hi, there are several warnings when building the project with docker:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/schemas@29.0.0',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.11.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/types@29.3.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.11.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-util@29.3.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.11.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-worker@29.3.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.11.2' }
npm WARN EBADENGINE }
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
```

```
added 886 packages, and audited 887 packages in 5m

126 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice 
npm notice New major version of npm available! 7.11.2 -> 9.6.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.2>
npm notice Run `npm install -g npm@9.6.2` to update!
npm notice
```

Example docker-compose file:

```yaml
version: "3.7"


networks:

  db_bridge:
    internal: true


services:

  hybooru-pg:
    image: postgres:latest
    container_name: hybooru-pg
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hybooru
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=hybooru
    networks:
      - db_bridge

  hybooru:
    build:
      context: .
    container_name: hybooru
    depends_on:
      - hybooru-pg
    restart: unless-stopped
    ports:
      - 80:80
#    volumes:
#      - /path/to/hydrus/db:/opt/hydrus/db
    networks:
      - db_bridge
      - default

```
